#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

echo '=============================================================';
echo ' [LNMP/Nginx] Amysql Host - AMH 3.2 ';
echo ' http://Amysql.com';
echo '';

CONFIGFILE="/root/amh/config.conf"
if [ -r ${CONFIGFILE} ]; then
	# Read the configfile if it's existing and readable
	source ${CONFIGFILE}
else
	MysqlPass='MysqlPassword';
	RootDir='alidata';
	BackupDir='alidata/www';
fi;
ftp_host='';
ftp_user='';
ftp_pass='';
ftp_log='/${RootDir}/wwwlogs/BRftp.log';
check_ftp_log='/${RootDir}/wwwlogs/BRftp_check.log';

function check_remote_ftp()
{
id=$1;
sql="SELECT remote_ip , remote_user , remote_password FROM amh.amh_backup_remote WHERE remote_type = 'FTP' AND remote_id = '${id}'";
set -- `mysql -uroot -p${MysqlPass} -B -N -e  "${sql}"`;
ftp_host=$1;
ftp_user=$2;
ftp_pass=$3;
if [ "$ftp_host" == '' ]; then
	echo '[Error] empty ftp host.';
	exit;
fi;
echo '' > ${check_ftp_log};
transmitted=`ping -c3 ${ftp_host} | grep transmitted | awk '{print $4}'`;
if [ "$transmitted" == 0 ]; then
	echo '[Error] time out.';
	exit;
else
ftp -n -v $ftp_host > ${check_ftp_log} << amh_ftp 
user $ftp_user $ftp_pass
type binary
ls
amh_ftp
fi;
grep -q '150 ' ${check_ftp_log} && echo "[OK] ftp://${ftp_user}@${ftp_host} connected successfully." || echo "[Error] ftp://${ftp_user}@${ftp_host} connection failed." ;
}


function post_remote_ftp()
{
backup_file=$1;
sql="SELECT remote_id , remote_ip , remote_user , remote_password , remote_path FROM amh.amh_backup_remote WHERE remote_type = 'FTP' AND remote_status = '1' ORDER BY remote_id ASC";
mysql -uroot -p${MysqlPass} -B -N -e "${sql}"  | while read result; do
	set -- $result;
	status=`check_remote_ftp $1`;
	if grep -q '150 ' ${check_ftp_log}; then
ftp_host=$2;
ftp_user=$3;
ftp_pass=$4;
ftp_path=$5;
dir=`echo $ftp_path | sed "s#/# #g"`;
dirs='';
for dir_name in $dir; do
	dirs="${dirs} \n mkdir ${dir_name} \n cd ${dir_name}";
done;
dirs=`echo -e $dirs`;
ftp -n -v $ftp_host > ${check_ftp_log} << amh_ftp 
user $ftp_user $ftp_pass
type binary
$dirs
put /${RootDir}/backup/${backup_file} ./${backup_file}
amh_ftp
		log_text="post ${backup_file} success.";
	else
		log_text="post ${backup_file} failed.";
	fi;

	echo "${status}  ${log_text}";
	sql_log="INSERT INTO amh.amh_log(log_user_id, log_text, log_ip) VALUES('0', '${status} \n $log_text', 'localhost')";
	mysql -uroot -p${MysqlPass} -B -N -e "${sql_log}";
done;
}


if [ "$1" == 'check' ]; then
	check_remote_ftp $2;
elif [ "$1" == 'post' ]; then
	post_remote_ftp $2;
fi;

