#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;
clear;
echo '=============================================================';
echo ' [LNMP/Nginx] Amysql Host - AMH 3.2 ';
echo ' http://Amysql.com';
echo '';


dates=`date +%Y-%m-%d`;
times=`date +%H:%M:%S`;
sys_name=`sed '1q' /etc/issue`;
sys_bit='32';
if [ `getconf WORD_BIT` == '32' ] && [ `getconf LONG_BIT` == '64' ] ; then
        sys_bit='64';
fi;
IP=`ifconfig  | grep 'inet addr:'| grep -v '127.0.0.*' | cut -d: -f2 | awk '{ print $1}'`;
cpu_name=`cat /proc/cpuinfo | grep 'model name' | awk '{ for(i=4 ; i<=NF; i++){ print $i} }'`;
cpu_num=`grep -c 'model name' /proc/cpuinfo`;
cpu_use=`top -n 2 -d 1 -b | grep 'Cpu(s)' | awk '{print $2}'`;
cpu_use=`echo $cpu_use | cut -d ' ' -f 2`;
up_time=`uptime | cut -f 1 -d "," | awk '{ print $3 $4 $5 $6}'`;
sys_load=`uptime | awk '{print $(NF-2), $(NF-1), $NF}' `;
ram_total=`free -m | grep 'Mem' | awk '{print $2}'`;
ram=`free -m | grep 'buffers/cache' | awk '{print $3}'`;

df_sum=0;
df_use=0;
while read result; do
       # set -- $result;
	
	i=0;
	for value in $result; do
		val='';
		if [ `echo $value | grep '^[0-9\.]\{1,\}M$'` ]; then
			val=`echo $value | sed 's#M##' | awk '{printf("%.2f", $1/1024)}'`;
		elif [ `echo $value | grep '^[0-9\.]\{1,\}G$'` ]; then
			val=`echo $value | sed 's#G##'`;
		fi;
		if [ "$val" != '' -a "$i" == 0 ]; then
			df_sum=`echo "$df_sum $val" | awk '{print $1+$2}'`;
			i=$[i+1];
		elif [ "$i" == 1 ]; then
			if [ "$val" != '' ]; then
				df_use=`echo "$df_use $val" | awk '{print $1+$2}'`;
			fi;
			break;
		fi;
	done;
done << EOT
`df -h`
EOT

echo "Linux:    ${sys_name} - ${sys_bit}BIT";
echo "UpTime:   ${up_time} online.";
echo "Time:     ${dates} ${times}";
echo "LA:       ${sys_load}";
echo "IP:       ${IP}";
echo "CPU:      ${cpu_use} ${cpu_num}*CPU - "${cpu_name};
echo "RAM:      ${ram}MB / ${ram_total}MB";
echo "HD:       ${df_use}GB / ${df_sum}GB";
echo "";
