#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin;

echo '=============================================================';
echo ' [LNMP/Nginx] Amysql Host - AMH 3.2 ';
echo ' http://Amysql.com';
echo '';

function MysqlManagement()
{
	if [ "$1" != '' ]; then
		selected=$1;
	else
		echo "[AMH] MySQL Management please select: (1~6)"
		select selected in  'start' 'stop' 'restart' 'reload' 'force-reload' 'exit'; do
			break;
		done;
	fi;

	if [ "$selected" == 'exit' ]; then
		exit;
	elif [ "$selected" != '' ]; then
		/etc/init.d/mysql $selected && echo "[OK] MySQL ${selected}";
		exit;
	else
		MysqlManagement;
		return;
	fi;
}
MysqlManagement $1;
